services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - 'astral-reading-by-soumya-postgres_data:/var/lib/postgresql/data'

#  redis:
#    image: 'redis:latest'
#    ports:
#      - '6379:6379'
#    volumes:
#      - 'produp-redis_data:/data'

volumes:
  astral-reading-by-soumya-postgres_data:
      driver: local
#  produp-redis_data:
#    driver: local
