# Generated by Django 5.1.3 on 2024-11-19 22:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HoroscopeSign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="horoscope-signs")),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Horoscope Sign",
                "verbose_name_plural": "Horoscope Signs",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CALL_CONSULTATION", "Call Consultation"),
                            ("WRITTEN_REPORT", "Written Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("regular_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discounted_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MonthlyHoroscope",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("month", models.DateField()),
                ("content", models.TextField()),
                (
                    "sign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.horoscopesign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monthly Horoscope",
                "verbose_name_plural": "Monthly Horoscopes",
                "unique_together": {("sign", "month")},
            },
        ),
        migrations.CreateModel(
            name="WeeklyHoroscope",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("week", models.DateField()),
                ("content", models.TextField()),
                (
                    "sign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.horoscopesign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weekly Horoscope",
                "verbose_name_plural": "Weekly Horoscopes",
                "unique_together": {("sign", "week")},
            },
        ),
    ]
