# Generated by Django 5.1.3 on 2024-11-19 22:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="weeklyhoroscope",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="weeklyhoroscope",
            name="sign",
        ),
        migrations.CreateModel(
            name="Horoscope",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("WEEKLY", "Weekly"), ("MONTHLY", "Monthly")],
                        max_length=7,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("content", models.TextField()),
                (
                    "sign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.horoscopesign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horoscope",
                "verbose_name_plural": "Horoscopes",
                "ordering": ["-start_date", "sign"],
                "unique_together": {("sign", "frequency", "start_date")},
            },
        ),
        migrations.DeleteModel(
            name="MonthlyHoroscope",
        ),
        migrations.DeleteModel(
            name="WeeklyHoroscope",
        ),
    ]
