# Generated by Django 5.1.3 on 2024-11-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_horoscope_options_testimonial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="horoscopesign",
            name="image",
        ),
        migrations.AddField(
            model_name="horoscopesign",
            name="icon_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
