# Generated by Django 5.1.3 on 2024-11-20 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_horoscopesign_image_horoscopesign_icon_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="horoscopesign",
            name="icon_name",
        ),
    ]
