# Generated by Django 5.1.3 on 2024-11-20 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_horoscopesign_icon_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="horoscopesign",
            options={
                "ordering": ["name"],
                "verbose_name": "Horoscope Sign",
                "verbose_name_plural": "Horoscope Signs",
            },
        ),
        migrations.AddField(
            model_name="testimonial",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="horoscope",
            name="sign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="horoscopes",
                to="core.horoscopesign",
            ),
        ),
    ]
