# Generated by Django 5.1.3 on 2024-11-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_horoscopesign_options_testimonial_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
