# Generated by Django 5.1.3 on 2024-11-21 02:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_testimonial_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrequentlyAskedQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("sortable_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Frequently Asked Question",
                "verbose_name_plural": "Frequently Asked Questions",
                "ordering": ["question"],
            },
        ),
    ]
